
PASS Calling navigator.credentials.get() without a valid matching interface.
PASS navigator.credentials.get() aborted with custom reason
PASS navigator.credentials.get() aborted with different objects
FAIL navigator.credentials.get() rejects when aborted after the promise creation promise_rejects_exactly: function "function() { throw e; }" threw object "NotSupportedError: Missing request type." but we expected it to throw object "Error: custom error"

